backend = "glx";
vsync = true;
use-damage = false;
unredir-if-possible = false;

fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 8;

animations = (
  {
    triggers = [ "open", "show" ];
    preset = "appear";
    duration = 0.12;
    scale = 0.96;
  },
  {
    triggers = [ "close", "hide" ];
    preset = "disappear";
    duration = 0.10;
    scale = 0.96;
  },
  {
    triggers = [ "geometry" ];
    preset = "geometry-change";
    duration = 0.12;
  }
);

opacity-rule = [
  "95:class_g = 'Gnome-terminal'",
  "95:class_i = 'gnome-terminal-server'"
];
